spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/securecapita
    password: letmein
    username: root
    jpa:
      database-platfrom: org.hibernate.dialect.MySQL8InnoDBDialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quoted_indentifiers: true
          dialect: org.hibernate.dialect.MySQL8InnoDBDialect
          format_sql: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/Front2
springdoc:
  swagger-ui:
    oauth:
      client-id: spring
      client-secret: RRzZOkjwglAnZ9vcoR1meSiYFN96f1Di
paypal:
  mode: sandbox
  client:
    id: ATkp649z9dvz_44GI_Xp1SvrCBm44lFMF3ABUab0EP21yt8Ln1wxNBeFjt4w5zuHkozX46x9kD2nLrn1
    secret: EMBH2uxsxdE5vVBlx5Co7xjoKVGfONtVw9eyjfZXl-yqrK2YQSucgO29-2NulTtlsgrfszFAmExB1_nV
